### ISSUE TITLE
Button not keyboard focusable

### ISSUE THREAD

**Issue by matjazpotocnik** [Toutouwai/FieldtypeDynamicOptions#2]
Is there a reason why a button for selecting images has disabled focus,  .isi-select-button { outline:none; } ?

**Comment by Toutouwai** [comment]
This is the FieldtypeDynamicOptions repo but your comment is about InputfieldSelectImages.

Nothing is preventing the button from being focused. What that rule does is remove the default browser focus style from the button. 

Is there a reason? Of course - I don't just type code at random. The reason is that all my modules are initially created for my own personal use and I have a dislike for ugly thick black outlines occurring on elements that have been focused by mouse click and not by keyboard. The core InputfieldImages module also does not have a focus style for its "Choose File" button so it's not that unusual a thing.

But very recently (like, after I coded this module) Chrome has thankfully changed their default user agent stylesheet so that the black outline is applied to the :focus-visible pseudo-class rather than :focus.
https://www.chromestatus.com/feature/5658873031557120
So I'll remove that rule in v0.1.3 which I'll release shortly.

**Comment by matjazpotocnik** [comment]
> This is the FieldtypeDynamicOptions repo but your comment is about InputfieldSelectImages.

Yeah, sorry.

> Nothing is preventing the button from being focused. What that rule does is remove the default browser focus style from the button.

That's what I wanted to say, but I chose impropriate wording. I'm using my own version of AdminThemeUikit, and there I have set up outlining. From an accessibility point of view, it's better to have a black outline than nothing, although the admin theme has other issues accessibility issues too. Thanks.
